// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nadosh.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nadosh.Infrastructure.Migrations
{
    [DbContext(typeof(NadoshDbContext))]
    [Migration("20260312073054_AddEdgeTaskExecutionBuffering")]
    partial class AddEdgeTaskExecutionBuffering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nadosh.Core.Models.AssessmentRun", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ApprovalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyDecisionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultSummaryJson")
                        .HasColumnType("text");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetScope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RunId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("Status");

                    b.HasIndex("ToolId");

                    b.ToTable("AssessmentRuns", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("text");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.AuthorizedTask", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ApprovalReference")
                        .HasColumnType("text");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text");

                    b.Property<string>("LeaseToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("RequiredCapabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ResultSummaryJson")
                        .HasColumnType("text");

                    b.Property<string>("ScopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaskKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TaskId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SiteId", "Status");

                    b.ToTable("AuthorizedTasks", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.CertificateObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DaysUntilExpiry")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelfSigned")
                        .HasColumnType("boolean");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KeySize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("SanList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignatureAlgorithm")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("Subject");

                    b.ToTable("CertificateObservations", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.CurrentExposure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CachedSummary")
                        .HasColumnType("text");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CveIds")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CveLastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CveSeverity")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HighestCvssScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.Property<string>("MacVendor")
                        .HasColumnType("text");

                    b.Property<string>("MitreTactics")
                        .HasColumnType("text");

                    b.Property<string>("MitreTechniques")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreatExplanation")
                        .HasColumnType("text");

                    b.Property<string>("ThreatLevel")
                        .HasColumnType("text");

                    b.Property<double?>("ThreatScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ThreatScoreCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TargetId", "Port", "Protocol")
                        .IsUnique();

                    b.ToTable("CurrentExposures", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.EdgeAgent", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<List<string>>("AdvertisedCapabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastKnownAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("AgentId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("SiteId");

                    b.HasIndex("Status");

                    b.ToTable("EdgeAgents", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.EdgeSite", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<List<string>>("AllowedCapabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("AllowedCidrs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ApprovalScopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataHandlingPolicyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SiteId");

                    b.HasIndex("Name");

                    b.ToTable("EdgeSites", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.EdgeTaskExecutionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AuthorizedTaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUploadError")
                        .HasColumnType("text");

                    b.Property<string>("LeaseToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LocalJobReference")
                        .HasColumnType("text");

                    b.Property<string>("LocalQueueName")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextUploadAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequeueRecommended")
                        .HasColumnType("boolean");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TaskKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizedTaskId")
                        .IsUnique();

                    b.HasIndex("NextUploadAttemptAt");

                    b.HasIndex("Status");

                    b.ToTable("EdgeTaskExecutionRecords", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.EnrichmentResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<long?>("CurrentExposureId")
                        .HasColumnType("bigint");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ObservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("CurrentExposureId");

                    b.HasIndex("ObservationId");

                    b.ToTable("EnrichmentResults", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.Observation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Banner")
                        .HasColumnType("text");

                    b.Property<string>("CveIds")
                        .HasColumnType("text");

                    b.Property<string>("CveSeverity")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("text");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("text");

                    b.Property<double?>("HighestCvssScore")
                        .HasColumnType("double precision");

                    b.Property<string>("HttpServer")
                        .HasColumnType("text");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("HttpTitle")
                        .HasColumnType("text");

                    b.Property<string>("JarmHash")
                        .HasColumnType("text");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.Property<string>("MacVendor")
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PipelineRetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("PipelineState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("PipelineStateChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PipelineWorkerId")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ProductVendor")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanRunId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<string>("ServiceVersion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SslExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SslIssuer")
                        .HasColumnType("text");

                    b.Property<string>("SslSubject")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt");

                    b.HasIndex("PipelineState");

                    b.HasIndex("TargetId");

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.ObservationHandoffDispatch", b =>
                {
                    b.Property<string>("DispatchKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SourceObservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<long?>("ProducedObservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text");

                    b.HasKey("DispatchKind", "SourceObservationId");

                    b.HasIndex("ProducedObservationId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("State");

                    b.ToTable("ObservationHandoffDispatches", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.RuleConfig", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MatcherDefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeverityMappingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RuleId", "Version");

                    b.ToTable("RuleConfigs", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.ScanRun", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CountsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RunId");

                    b.ToTable("ScanRuns", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.Stage1Dispatch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("TargetIp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ObservationLinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenObservationCount")
                        .HasColumnType("integer");

                    b.Property<string>("PortsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text");

                    b.HasKey("BatchId", "TargetIp");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("State");

                    b.ToTable("Stage1Dispatches", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.SuppressionRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cidr")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .HasColumnType("text");

                    b.Property<string>("TargetIp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TargetIp");

                    b.ToTable("SuppressionRules", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.Target", b =>
                {
                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("AsnInfo")
                        .HasColumnType("text");

                    b.Property<int?>("AsnNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AsnOrganization")
                        .HasColumnType("text");

                    b.Property<int>("Cadence")
                        .HasColumnType("integer");

                    b.Property<string>("CidrSource")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("DataCenter")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EnrichmentCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeoCountry")
                        .HasColumnType("text");

                    b.Property<double>("InterestScore")
                        .HasColumnType("double precision");

                    b.Property<string>("IspName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastScheduled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStateChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MacEnrichmentCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacVendor")
                        .HasColumnType("text");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextScheduled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenPortCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("OwnershipTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("ReverseDns")
                        .HasColumnType("text");

                    b.Property<int>("StateChangeCount")
                        .HasColumnType("integer");

                    b.HasKey("Ip");

                    b.HasIndex("NextScheduled");

                    b.ToTable("Targets", (string)null);
                });

            modelBuilder.Entity("Nadosh.Core.Models.AuthorizedTask", b =>
                {
                    b.HasOne("Nadosh.Core.Models.EdgeAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nadosh.Core.Models.EdgeSite", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nadosh.Core.Models.EdgeAgent", b =>
                {
                    b.HasOne("Nadosh.Core.Models.EdgeSite", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
