using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nadosh.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddPartitioning : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                -- Create partition functions/triggers or manual SQL for partitioning
                -- First we need to convert the existing table to a partitioned table.
                -- However, in PostgreSQL, to change a table to partitioned, we have to recreate it.
                -- Since we are doing this early, we can drop and recreate before data exists.
                
                DROP TABLE ""Observations"";
                
                CREATE TABLE ""Observations"" (
                    ""Id"" bigint GENERated BY DEFAULT AS IDENTITY,
                    ""TargetId"" text NOT NULL,
                    ""ObservedAt"" timestamp with time zone NOT NULL,
                    ""Port"" integer NOT NULL,
                    ""Protocol"" text NOT NULL,
                    ""State"" text NOT NULL,
                    ""LatencyMs"" integer,
                    ""Fingerprint"" text,
                    ""EvidenceJson"" jsonb,
                    ""ScanRunId"" text,
                    CONSTRAINT ""PK_Observations"" PRIMARY KEY (""Id"", ""ObservedAt"")
                ) PARTITION BY RANGE (""ObservedAt"");

                CREATE INDEX ""IX_Observations_TargetId"" ON ""Observations"" (""TargetId"");
                CREATE INDEX ""IX_Observations_ObservedAt"" ON ""Observations"" (""ObservedAt"");

                -- Create initial partitions for this year
                CREATE TABLE ""Observations_y2026m03"" PARTITION OF ""Observations"" FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
                CREATE TABLE ""Observations_y2026m04"" PARTITION OF ""Observations"" FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
                CREATE TABLE ""Observations_y2026m05"" PARTITION OF ""Observations"" FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE ""Observations"";
                
                CREATE TABLE ""Observations"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
                    ""TargetId"" text NOT NULL,
                    ""ObservedAt"" timestamp with time zone NOT NULL,
                    ""Port"" integer NOT NULL,
                    ""Protocol"" text NOT NULL,
                    ""State"" text NOT NULL,
                    ""LatencyMs"" integer,
                    ""Fingerprint"" text,
                    ""EvidenceJson"" jsonb,
                    ""ScanRunId"" text,
                    CONSTRAINT ""PK_Observations"" PRIMARY KEY (""Id"")
                );

                CREATE INDEX ""IX_Observations_TargetId"" ON ""Observations"" (""TargetId"");
                CREATE INDEX ""IX_Observations_ObservedAt"" ON ""Observations"" (""ObservedAt"");
            ");
        }
    }
}
